changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot
  categories:
    - title: 🚧 Breaking Changes
      labels:
        - breaking-change
    - title: ✨ Enhancements
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bugfix
    - title: 🛠 Other Changes
      labels:
        - "*"